# -*- coding: utf-8 -*-
"""Aula3C.ípynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HKU4K-7xbeZHsch6_EI97UTEeqx9tngk
"""

# Preparando o ambiente no Google Drive:

#importando a biblioteca
from google.colab import drive

# Isso irá pedir sua autorização
drive.mount('/content/drive')

# Agora, seu Drive estará disponível em: /content/drive/My Drive
! pip install geopandas

import geopandas as gpd

# Ler os dados
polygons = gpd.read_file('/content/drive/My Drive/GEOJSON/Bairros.geojson')
points = gpd.read_file('/content/drive/My Drive/GEOJSON/teste.geojson')

print (polygons.head())
print (points.head())

# Essa cópia é feita pois os pontos serão designados aos polígonos dos bairros
pts = points.copy()
pts_in_polys = []

# Conta quantos pontos há em cada polígono
for i, poly in polygons.iterrows():

    pts_in_this_poly = []

    for j, pt in pts.iterrows():
        if poly.geometry.contains(pt.geometry):
            pts_in_this_poly.append(pt.geometry)
            pts = pts.drop([j])

    pts_in_polys.append(len(pts_in_this_poly))
print (pts_in_polys)

# Adiciona o número de pontos ao data frame dos polígonos
polygons['number of points'] = pts_in_polys

#Mostra a tabela
print (polygons.head())
# Mostra estatísticas básicas
polygons.describe()

"""## Agora, criamos o mapa:"""

import folium

attr = ('&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors &copy; <a href="https://carto.com/attributions">CARTO</a>')
tiles = ('https://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}{r}.png')

m = folium.Map (location = [-25.5,-49.3],tiles = tiles, attr = attr, zoom_start =  11)

bins = list(polygons['number of points'].quantile([0, 0.25, 0.5, 0.75, 1]))
#Colors: 'BuGn', 'BuPu', 'GnBu', 'OrRd', 'PuBu', 'PuBuGn', 'PuRd', 'RdPu','YlGn', 'YlGnBu', 'YlOrBr', and 'YlOrRd'.

folium.Choropleth(
 geo_data=polygons,
 name='estacionamentos por bairro',
 columns=['OBJECTID', 'number of points'],
 data=polygons,
 key_on='feature.properties.OBJECTID',
 fill_color= 'RdPu',
 fill_opacity = 1,
 line_opacity = 1,
 legend_name='Pré-escolas por bairro',
 bins=bins,
 reset=True
).add_to(m)

folium.LayerControl().add_to(m)
m.save("/content/drive/My Drive/GEOJSON/index_estac.html")
m

"""## E um gráfico"""

import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
result = polygons.groupby(["NOME"])['number of points'].aggregate(np.median).reset_index().sort_values('number of points')
plt.figure(figsize=(20,15))
sns.barplot(y='NOME',x='number of points', data = result, color = 'pink' )
plt.xlabel('Quantidade')
plt.ylabel('Bairros')
plt.show()
